AdguardTeam/FiltersRegistry

.travis.yml, push.sh
Do not build for Travis commits
=> travis integration

package.json
HTML filtering and $replace rules for the Firefox add-on
=> Using filters-compiler 1.0.5

filters/ThirdParty/filter_237_PolishAnnoyance/metadata.json
=> PolishAnnoyance  - added lang tag

filters/ThirdParty/filter_245_AlleBlock/metadata.json
Replaced AlleBlock list URL https://github.com/AdguardTeam/FiltersRegistry/issues/18
=> Replaced AlleBlock list URL

filters/ThirdParty/filter_104_EasyListChina/metadata.json
=> Update metadata.json -- EasyList China

filters/filter_16_French/exclusions.txt
Reverts AdguardTeam/FiltersRegistry#49
The issue was fixed in Liste FR.
=> Revert "uniondht.org https://github.com/AdguardTeam/AdguardFilters/issues/15607"

filters/filter_16_French/exclusions.txt
https://forum.adguard.com/index.php?threads/23801/
=> nitroflare.com - Liste FR issue

filters/ThirdParty/filter_216_PolskiFiltr/metadata.json, filters/ThirdParty/filter_227_List-KR/exclusions.txt, filters/exclusions.txt, filters/filter_16_French/exclusions.txt, filters/filter_2_English/exclusions.txt, filters/filter_6_German/exclusions.txt, package.json
nested condition directives
enabled 216 Polish filter
=> updated compiler

filters/ThirdParty/filter_222_ABPPersian/filter.txt, filters/ThirdParty/filter_222_ABPPersian/template.txt
updated source and removed few dangerous rules
=> https://github.com/AdguardTeam/AdguardFilters/issues/21320

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
Fixing search with EasyPrivacy enabled
https://github.com/AdguardTeam/AdguardFilters/issues/24772
=> Fixing search with EasyPrivacy enabled

filters/ThirdParty/filter_102_ABPindo/template.txt
Site shows error.
https://github.com/AdguardTeam/AdguardFilters/issues/22226#issuecomment-438551002
=> Fixing cnet.com

filters/exclusions.txt
https://github.com/AdguardTeam/ExtendedCss/issues/75
=> travis failed to build filters - extended CSS issue 

filters/ThirdParty/filter_104_EasyListChina/template.txt
Fixing broken videos
https://github.com/AdguardTeam/AdguardFilters/issues/25630#issuecomment-441495214
=> avgle.com #25630

package.json
fix generator for obsolete filters
=> updated compiler:

filters/ThirdParty/filter_210_Spam404/template.txt
=> sentry.mba https://forum.adguard.com/index.php?threads/sentry-mba.30010/

filters/ThirdParty/filter_210_Spam404/template.txt
=> nulled.to https://forum.adguard.com/index.php?threads/nulled-to-incorrect-blocking.30024

filters/ThirdParty/filter_204_PeterLowesList/template.txt
Fixing broken page
https://github.com/AdguardTeam/AdguardFilters/issues/26571
=> adstage.io #26571

filters/ThirdParty/filter_212_RUAdListCounters/metadata.json, filters/ThirdParty/filter_213_RUAdListBitBlock/metadata.json
https://github.com/AdguardTeam/AdguardForAndroid/issues/2386
=> Added language tags to Ru Adlist

package-lock.json, package.json, yarn.lock
=> Updated filters-compiler

filters/ThirdParty/filter_227_List-KR/metadata.json
https://github.com/List-KR/List-KR/commit/d212deff951ec433fb2960f3c9c4a6f5ba6cb8ba
=> Update List-KR's Homepage

filters/ThirdParty/filter_113_ListeFR/template.txt
Rule will fix self-promo on main page.
=> kinopolis.de - fixing self-promo on start page

filters/ThirdParty/filter_219_ChinaListAndEasyList/metadata.json
Disabled ChinaList+EasyList for a couple of days, because it causes issue with filters build.
=> Disabled ChinaList+EasyList

filters/ThirdParty/filter_232_KADPrzekrety/metadata.json, filters/ThirdParty/filter_232_KADPrzekrety/template.txt
KAD is now managed by @PolishFiltersTeam.
=> KAD has new house

filters/filter_12_Safari/metadata.json, filters/filter_2_English/template.txt, package-lock.json, package.json, yarn.lock
Included Safari filter to Base filter.
Safari filter marked as obsolete.
https://github.com/AdguardTeam/AdguardFilters/pull/30207
=> Safari filter rework

filters/ThirdParty/filter_210_Spam404/template.txt
Fixing broken site
https://forum.adguard.com/index.php?threads/dropbbase-com-incorrect-blocking.31248/
=> dropbase.com https://forum.adguard.com/index.php?threads/dropbbase-com-incorrect-blocking.31248/

filters/exclusions.txt
=> Excluding problematic rule

filters/ThirdParty/filter_104_EasyListChina/template.txt
Fixing broken pictures
https://github.com/AdguardTeam/AdguardFilters/issues/31298
=> Fixing broken pictures

filters/exclusions.txt
Excluding dangerous rule which breaks search results
https://github.com/AdguardTeam/AdguardFilters/issues/31447
=> ebay.com - fixing product results

filters/exclusions.txt
=> Fix https://github.com/AdguardTeam/AdguardFilters/issues/28868 kaidee.com

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
Fixing site https://github.com/AdguardTeam/AdguardFilters/issues/31746
=> Fixing site https://github.com/AdguardTeam/AdguardFilters/issues/31746

filters/exclusions.txt
Fixed in EasyList
https://github.com/AdguardTeam/FiltersRegistry/pull/195
=> Fix windowscentral.com

filters/ThirdParty/filter_209_Prebake/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/37106
=> Fix allianz.hu

filters/exclusions.txt
fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/116
=> fix https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/116

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/40624
=> Fix fox-fan.tv 

filters/ThirdParty/filter_122_FanboysAnnoyances/metadata.json, filters/ThirdParty/filter_123_FanboysSocialBlockingList/metadata.json, filters/ThirdParty/filter_204_PeterLowesList/metadata.json, filters/ThirdParty/filter_208_MalwareDomains/metadata.json, filters/ThirdParty/filter_210_Spam404/metadata.json, filters/ThirdParty/filter_215_FanboysEnancedTrackingList/metadata.json, filters/ThirdParty/filter_229_IdontCareAboutCookies/metadata.json, filters/ThirdParty/filter_241_FanboyCookiemonster/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/issues/222
=> Fix #222 - Updated filters descriptions

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/41309
=> Fix #41309 liveam.tv

filters/ThirdParty/filter_200_ABPJapaneseFilters/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/34795#issuecomment-544906454
=> Fix twitter.com [ABP Japanese Filters]

filters/ThirdParty/filter_112_ListeAR/metadata.json, filters/ThirdParty/filter_112_ListeAR/template.txt
Location moved from code.google.com.
=> Fix LIste AR location

filters/ThirdParty/filter_211_YanFung/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/42884
=> Fix mail.google.com [YanFung mobile ads filter]

filters/ThirdParty/filter_212_RUAdListCounters/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/43031
=> Fix Yandex Elements extension 

filters/ThirdParty/filter_211_YanFung/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/43201
=> Fix typingclub.com

filters/ThirdParty/filter_211_AntiAdblockKillerReek/template.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/251
=> Fix #251 myreadingmanga.info

filters/exclusions.txt
I disabled the rule on Windows app and I do not see any issues.
=> Excluding genericblock gofeminin.de

filters/ThirdParty/filter_115_RUAdList/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/43124#issuecomment-549806796
=> Fixing RU AdList issue on radikal.ru

filters/ThirdParty/filter_209_Prebake/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/44636
=> Fixing nhk.or.jp

filters/ThirdParty/filter_104_EasyListChina/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/44417
=> fix #264 m.douban.com

filters/ThirdParty/filter_241_FanboyCookiemonster/metadata.json
https://github.com/easylist/easylist/blob/master/fanboy-cookie.template
=> 'Fanboy's Cookiemonster List' renamed to 'EasyList Cookie List'

filters/ThirdParty/filter_121_VoidGr/metadata.json
=> Enable void.gr filter

filters/ThirdParty/filter_113_ListeFR/metadata.json
does not help. Must be fixed in compiler
=> Revert "Temporary disable Liste FR because filters fail"

filters/exclusions.txt
Issue is fixed https://github.com/AdguardTeam/FiltersCompiler/issues/31
=> Remove exclusions

filters/ThirdParty/filter_229_IdontCareAboutCookies/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/50576
=> Fix i-dont-care-about-cookies

filters/ThirdParty/filter_115_RUAdList/template.txt
https://github.com/AdguardTeam/Scriptlets/issues/73
https://github.com/AdguardTeam/AdguardFilters/issues/51477
=> Fix fastpic.ru

filters/exclusions.txt
https://github.com/easylist/easylist/commit/d35f46e16356c39b638f5a5541e2aa01a9e7f72d
=> Fix youtube.com - excluding the rule which unblocks video ads

package.json
Hotfix of Scriptlets and FiltersCompiler libs
=> Updated version to 1.0.27

filters/ThirdParty/filter_102_ABPindo/metadata.json, filters/ThirdParty/filter_120_AdBlockID/metadata.json
Details: https://github.com/AdguardTeam/FiltersRegistry/issues/235
=> Make Indonesian filter AdBlockID recommended

filters/ThirdParty/filter_222_ABPPersian/filter.txt, filters/ThirdParty/filter_222_ABPPersian/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/53365 + updated 'Adblock-Persian list'
=> Fix digistyle.com + updated 'Adblock-Persian list'

filters/ThirdParty/filter_222_ABPPersian/filter.txt, filters/ThirdParty/filter_222_ABPPersian/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/53500
Fixed incorrect blocking which is caused by `Adblock-Persian list` filter.
=> Fix wow.gamepedia.com

filters/ThirdParty/filter_209_Prebake/template.txt, filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/53816
=> Fix dunyagrup.com

filters/ThirdParty/filter_201_WebAnnoyancesUltralist/metadata.json, package.json
FiltersCompiler release - https://github.com/AdguardTeam/FiltersCompiler/releases/tag/v1.0.53
=> Updated version to 1.0.29 and FiltersCompiler to v1.0.53

filters/exclusions.txt
The same issue as lately - https://github.com/AdguardTeam/FiltersRegistry/pull/337
=> Excluded $popup rule

filters/ThirdParty/filter_201_WebAnnoyancesUltralist/metadata.json
Reverts AdguardTeam/FiltersRegistry#340
=> Revert "Temporary disabled Web Annoyances Ultralist due to incompatible '!#include' directive"

filters/ThirdParty/filter_220_CJXsAnnoyanceList/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/56548
=> Fix #347 wk.baidu.com

.travis.yml, index.js, package.json
This pr have to merged after FiltersCompiler release to avoid problem with arguments amount passed there.
=> Updated FiltersCompiler and added report file

filters/ThirdParty/filter_249_NorwegianList/metadata.json, index.js, package.json, yarn.lock
* updated FiltersCompiler to v1.0.55
* updated version to 1.0.31
* removed blacklist-domains
* enabled 249 Norwegian filter
=> Updated FiltersCompiler to v1.0.55

filters/exclusions.txt
$redirect processed by trust-levels
=> Removed $redirect from exclusions.txt

filters/ThirdParty/filter_200_ABPJapaneseFilters/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/issues/360#issuecomment-653946831
=> Added `obsolete` tag to ABP Japanese filter's metadata

filters/ThirdParty/filter_117_PolishSubFilters/metadata.json
https://uploads.adguard.com/slbdzdrokv4v.png
=> disable 117th filter

filters/ThirdParty/filter_222_ABPPersian/filter.txt, filters/ThirdParty/filter_222_ABPPersian/template.txt, filters/exclusions.txt
Not seeing a way to contact author.
https://github.com/AdguardTeam/AdguardFilters/issues/60229
=> fix australiangeographic.com.au https://github.com/AdguardTeam/AdguardFilters/issues/60229

filters/ThirdParty/filter_123_FanboysSocialBlockingList/template.txt
[#60569](https://github.com/AdguardTeam/AdguardFilters/issues/60569)
=> fix #60569 theverge.com

filters/ThirdParty/filter_240_BarbBlock/metadata.json
https://uploads.adguard.com/slbdzdrbtgzi.png
=> temporary disable BarbBlock

filters/ThirdParty/filter_229_IdontCareAboutCookies/template.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/379
mobile issue
=> Fix #379 news.google.com

filters/exclusions.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/392
=> Fix #392 airbattle.xyz

filters/exclusions.txt
=> Excluded bad FR rule

filters/ThirdParty/filter_234_ROList2/metadata.json
https://uploads.adguard.com/slbdzdrl6de6.png
=> temporary disable ROLIST2

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/70449
=> fix #70449 wallet.nimiq.com

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/71151
=> fix #71151 survey3.medallia.com

.github/workflows/workflow.yaml, filters/ThirdParty/filter_235_adblock-iran/metadata.json, filters/ThirdParty/filter_235_adblock-iran/template.txt
https://uploads.adguard.com/slbdzdrc03en.png
=> update subscriptionUrl for Iranian filter

filters/ThirdParty/filter_235_adblock-iran/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/pull/414#discussion_r556103485
=> Changed trustLevel for Iranian filter to High

filters/ThirdParty/filter_228_xinggsf/metadata.json, filters/ThirdParty/filter_228_xinggsf/template.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/419
- updated filter source;
- changed `trustlevel` to `high`(it seems the scriptlets are good)
=> Updated 'xinggsf' filter metadata

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/73073
=> Excluded anOptions andiadblock script baits(Liste-FR)

filters/ThirdParty/filter_122_FanboysAnnoyances/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/75860
=> fix #75860 disgustingmen.com

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/76563
=> fix #76563 click.email.wbez.org

package.json, yarn.lock
\+ set-cookie-reload support
\+ set-constant empty string arg
\+ platforms properties for metadata
=> update compiler to v1.1.10

filters/ThirdParty/filter_229_IdontCareAboutCookies/filter.txt
=> Removed reduntant $badfilter from "I don't care about cookies"

filters/ThirdParty/filter_121_VoidGr/metadata.json
Cannot be downloaded due to HTTPS issue(HTTP redirected to HTTPS and also failed)
=> Temporary disabled Greek AdBlock Filter

README.md, filters/filter_10_Useful/metadata.json, filters/filter_11_Mobile/metadata.json, filters/filter_12_Safari/metadata.json, filters/filter_13_Turkish/metadata.json, filters/filter_14_Annoyances/metadata.json, filters/filter_15_DnsFilter/metadata.json, filters/filter_16_French/metadata.json, filters/filter_224_Chinese/metadata.json, filters/filter_2_English/metadata.json, filters/filter_3_Spyware/metadata.json, filters/filter_4_Social/metadata.json, filters/filter_5_Experimental/metadata.json, filters/filter_6_German/metadata.json, filters/filter_7_Japanese/metadata.json, filters/filter_8_Dutch/metadata.json, filters/filter_9_Spanish/metadata.json
=> Removed language code from homepage URLs

filters/exclusions.txt
after a while, the corresponding exceptions can be removed
=> Excluded few anti-adblock baits

filters/exclusions.txt
Related to https://github.com/AdguardTeam/FiltersRegistry/pull/454/files
=> changed regex of exlusion

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/79058
=> fix #79058 sadhguru.us7.list-manage.com

filters/ThirdParty/filter_222_ABPPersian/template.txt
Updated ABPersian, removed dangerous rules
=> Updated ABPPersian

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/80453
=> fix #80453 xda-developers.com

filters/ThirdParty/filter_112_ListeAR/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/80936
=> dailymotion.com

filters/ThirdParty/filter_119_IcelandicABPList/metadata.json
`Retry downloading: https://adblock.gardar.net/is.abp.txt`
=> temporary disable 119 Icelandic ABP List

filters/ThirdParty/filter_222_ABPPersian/template.txt, filters/exclusions.txt
=> Removed bad rules from ABPPersian and xinggsf

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/81810
=> fix #81810 app.tookanapp.com

filters/filter_11_Mobile/metadata.json, filters/filter_12_Safari/metadata.json, filters/filter_13_Turkish/metadata.json, filters/filter_14_Annoyances/metadata.json, filters/filter_15_DnsFilter/metadata.json, filters/filter_16_French/metadata.json, filters/filter_1_Russian/metadata.json, filters/filter_224_Chinese/metadata.json, filters/filter_2_English/metadata.json, filters/filter_3_Spyware/metadata.json, filters/filter_4_Social/metadata.json, filters/filter_5_Experimental/metadata.json, filters/filter_6_German/metadata.json, filters/filter_7_Japanese/metadata.json, filters/filter_8_Dutch/metadata.json, filters/filter_9_Spanish/metadata.json
homepage urls should be changed for our filters
https://uploads.adguard.com/slbdzdrrkuu4.png
=> Fix AdGuard filters homepage urls

filters/ThirdParty/filter_222_ABPPersian/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/81637
=> fix #81637 songsara.net

filters/ThirdParty/filter_241_FanboyCookiemonster/metadata.json
=> Changed EasyList Cookie List trustLevel

filters/exclusions.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/484
=> Fix gwdang.com #484

filters/exclusions.txt
Way too generic. BTW is exclusion for ABP Japanese Filter still needed?
=> Fix https://github.com/AdguardTeam/AdguardFilters/issues/84173

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/86351
=> fix #86351 toloka.to

README.md
<details><summary>Screenshot:</summary>
</details><br/>
=> Fix a gap in the readme file

filters/exclusions.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/280
=> Removed redundant exclusion ##^

package.json, yarn.lock
* updated filters-compiler to v1.1.21
* fixed #400
=> Update filters-compiler to v1.1.21

filters/ThirdParty/filter_115_RUAdList/metadata.json, filters/ThirdParty/filter_212_RUAdListCounters/metadata.json, filters/ThirdParty/filter_213_RUAdListBitBlock/metadata.json
According to our new rules, these filters don't pass them.
=> Disable Ru AdList filters

filters/filter_8_Dutch/template.txt
https://github.com/AdguardTeam/AdguardFilters/pull/89302
=> Edit template.txt for AG Dutch filter

filters/ThirdParty/filter_249_NorwegianList/metadata.json
DandelionSprout fixed issue
https://github.com/DandelionSprout/adfilt/commit/e04e6e090a0267879b0fbf1061b4987b33c38980
=> Enable 249 filter

filters/ThirdParty/filter_228_xinggsf/metadata.json
According to https://github.com/AdguardTeam/FiltersRegistry/pull/508, now it's woking fine. Let's check this before turning on the filter again.
=> Enable xinggsf filter

package.json, yarn.lock
do not count decimal part of max number while optimization
=> update compiler to v1.1.22

filters/ThirdParty/filter_115_RUAdList/metadata.json, filters/ThirdParty/filter_115_RUAdList/template.txt, filters/ThirdParty/filter_212_RUAdListCounters/metadata.json, filters/ThirdParty/filter_212_RUAdListCounters/template.txt, filters/ThirdParty/filter_213_RUAdListBitBlock/metadata.json
RU Adlist as incompatible; BitBlock - in according to https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository
Related to https://github.com/AdguardTeam/FiltersRegistry/pull/507
=> Removed RU Adlist and BitBlock filters

package.json
* updated FiltersCompiler to v1.1.27
* incremented version to v1.0.40
=> Update FiltersCompiler to v1.1.27

filters/ThirdParty/filter_227_List-KR/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/issues/524
=> Fix 524 - metadata

filters/ThirdParty/filter_218_EstonianList/metadata.json
Let's disable this filter temporary, he's not available right now.
<details><summary>Screenshot:</summary>
</details><br/>
=> Temporary disable Estonian List

filters/ThirdParty/filter_240_BarbBlock/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/issues/546
=> Disable BarbBlock

filters/ThirdParty/filter_115_RUAdList/metadata.json, filters/ThirdParty/filter_213_RUAdListBitBlock/metadata.json, filters/ThirdParty/filter_240_BarbBlock/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/pull/548#issuecomment-981433989
=> Changed a bit names for obsolete filters

filters/ThirdParty/filter_232_KADPrzekrety/metadata.json, filters/ThirdParty/filter_232_KADPrzekrety/template.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/552#issuecomment-1001436681
=> Some changes on the KAD filter

filters/ThirdParty/filter_228_xinggsf/metadata.json, filters/ThirdParty/filter_228_xinggsf/template.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/560
=> xinggsf url has changed

filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/metadata.json, filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/template.txt
https://old.reddit.com/r/Adguard/comments/s6vbvl/online_malicious_url_blocklist_problem/
=> updating source Online Malicious URL BLocklist

filters/ThirdParty/filter_118_EasyPrivacy/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/103955
=> fix #103955 parcelapp.net

filters/ThirdParty/filter_204_PeterLowesList/metadata.json
Third-party filters build failed.
=> Temporary disabled Peter Lowe's Blocklist

filters/ThirdParty/filter_214_ABPVNList/metadata.json
According to the https://github.com/AdguardTeam/FiltersRegistry/issues/576, I think we can consider changing the trust level.
=> ABPVN List - trust level

filters/ThirdParty/filter_204_PeterLowesList/metadata.json
=> Removed lang tag from Peter Lowe's Blocklist metadata

package.json
Resolves this issue: https://github.com/AdguardTeam/FiltersCompiler/issues/138
=> Updated FiltersCompiler to v1.1.38

filters/ThirdParty/filter_201_WebAnnoyancesUltralist/metadata.json, filters/ThirdParty/filter_219_ChinaListAndEasyList/metadata.json
Temporary disabled 201 and 219 because filters build failed
=> Temporary disabled 201 and 219

filters/ThirdParty/filter_201_WebAnnoyancesUltralist/metadata.json, filters/ThirdParty/filter_219_ChinaListAndEasyList/metadata.json
Reverts AdguardTeam/FiltersRegistry#584
=> Revert "Temporary disabled 201 and 219"

filters/ThirdParty/filter_204_PeterLowesList/metadata.json, filters/ThirdParty/filter_204_PeterLowesList/template.txt
Moved PeterLowesList to privacy group
=> Moved PeterLowesList to privacy group

filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/metadata.json, filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/template.txt
https://github.com/AdguardTeam/AdguardFilters/issues/119502
=> Update to new source

filters/ThirdParty/filter_223_FanboySwedish/metadata.json, filters/ThirdParty/filter_226_FanboyVietnamese/metadata.json, filters/ThirdParty/filter_230_FanboyEspanol/metadata.json
Fanboy's Swedish, Fanboy's Vietnamese, Fanboy's Spanish/Portuguese
Maybe also translations must be removed. Or not.
=> Disabled obsolete filters Fanboy's filters

filters/ThirdParty/filter_122_FanboysAnnoyances/metadata.json, filters/ThirdParty/filter_122_FanboysAnnoyances/template.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/635
=> Fanboy's Annoyances - new subscription url

filters/exclusions.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/636
[Regex](https://regex101.com/r/5DGFet/1)
=> `redirect:` in `exclusions.txt` is too broad

filters/exclusions.txt
https://github.com/xinggsf/Adblock-Plus-Rule/issues/52
=> exclude p2p rule from xinggsf

filters/ThirdParty/filter_111_LatvianList/metadata.json
Related to errors https://github.com/AdguardTeam/FiltersRegistry/pull/644 and https://github.com/AdguardTeam/FiltersRegistry/pull/645
=> Latvian List - temporary disable this filter

filters/ThirdParty/filter_111_LatvianList/metadata.json
https://github.com/Latvian-List/adblock-latvian/issues/7
=> Revert "Latvian List - temporary disable this filter"

filters/filter_18_Annoyances_Cookies/metadata.json, filters/filter_19_Annoyances_Popups/metadata.json, filters/filter_20_Annoyances_MobileApp/metadata.json, filters/filter_21_Annoyances_Other/metadata.json, filters/filter_22_Annoyances_Widgets/metadata.json
Related to https://github.com/AdguardTeam/FiltersRegistry/pull/640
=> Removed recommended tags from new annoyances filters

.gitignore, README.md, custom_platforms.js, index.js, package.json, yarn.lock
https://github.com/AdguardTeam/FiltersCompiler/issues/152
=> Filters compiler should remove cosmetic rules with modifiers for the platforms where they're not supported

filters/filter_11_Mobile/template.txt
according to https://github.com/AdguardTeam/AdguardFilters/pull/127923
=> Split allowlist mobile

filters/.gitattributes
enabled adblock syntax detection by linguist
=> Changed linguist attributes

filters/ThirdParty/filter_236_ROad-Block/metadata.json, filters/ThirdParty/filter_236_ROad-Block/template.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/669
=> Scriptlet support for `road-block`

filters/filter_2_English/template.txt
Related PRs:
https://github.com/AdguardTeam/HostlistCompiler/pull/37
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1042
https://github.com/AdguardTeam/AdguardFilters/pull/129688
=> Rename English filter to Base in paths

filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/metadata.json
Compiler cannot download it at the moment.
=> Temporary disabled Online Malicious URL Blocklist

filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/metadata.json
https://github.com/AdguardTeam/AdguardFilters/issues/134584
The reporter complains that the filter is not being updated.
=> enable Online Malicious URL Blocklist

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2240
=> temporary exclusion of bad List-KR rule 

filters/ThirdParty/filter_119_IcelandicABPList/metadata.json, filters/filter_2_Base/template.txt
Related to https://github.com/AdguardTeam/FiltersRegistry/pull/701.
=> Removed a parameter from Icelandic filter.

filters/ThirdParty/filter_119_IcelandicABPList/template.txt, filters/filter_2_Base/template.txt
[Reverted `notOptimzed` parameter to AdGuard Base](https://github.com/AdguardTeam/FiltersRegistry/pull/703) template and removed similar one from Icelandic filter.
=> Reverted one change

package.json, report.txt, yarn.lock
https://github.com/AdguardTeam/FiltersCompiler/blob/master/CHANGELOG.md#v1172
=> update compiler to v1.1.72

package.json, yarn.lock
https://github.com/AdguardTeam/FiltersCompiler/blob/master/CHANGELOG.md#v1173
=> update compiler to v1.1.73

filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/metadata.json
Reverts AdguardTeam/FiltersRegistry#707
https://github.com/AdguardTeam/FiltersRegistry/pull/707
=> Revert "Disabled Online Malicious URL Blocklist due to failed builds"

filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/metadata.json
Reverts AdguardTeam/FiltersRegistry#714
Build still fails
=> Revert "Revert "Disabled Online Malicious URL Blocklist due to failed builds""

README.md, filters/filter_10_Useful/metadata.json, filters/filter_11_Mobile/metadata.json, filters/filter_13_Turkish/metadata.json, filters/filter_14_Annoyances/metadata.json, filters/filter_15_DnsFilter/metadata.json, filters/filter_16_French/metadata.json, filters/filter_17_TrackParam/metadata.json, filters/filter_18_Annoyances_Cookies/metadata.json, filters/filter_19_Annoyances_Popups/metadata.json, filters/filter_1_Russian/metadata.json, filters/filter_20_Annoyances_MobileApp/metadata.json, filters/filter_21_Annoyances_Other/metadata.json, filters/filter_224_Chinese/metadata.json, filters/filter_22_Annoyances_Widgets/metadata.json, filters/filter_2_Base/metadata.json, filters/filter_3_Spyware/metadata.json, filters/filter_4_Social/metadata.json, filters/filter_5_Experimental/metadata.json, filters/filter_6_German/metadata.json, filters/filter_7_Japanese/metadata.json, filters/filter_8_Dutch/metadata.json, filters/filter_9_Spanish/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/issues/726
=> Replace the old knowledge base links with the new one

filters/ThirdParty/filter_245_AlleBlock/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/issues/411#issuecomment-1445158649
Seems the filter is really obsolete.
=> AlleBlock - obsolete filter

README.md
https://github.com/AdguardTeam/FiltersRegistry/issues/737
=> Exchange the example in `README.md`

locales/tr/filters.json
Updated translations as requested.
Validation was successful.
=> Updating translations

package.json, yarn.lock
=> update compiler to v1.1.77

filters/filter_1_Russian/template.txt
=> Removed includes for old Russian filter location

filters/exclusions.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/753
also removed redundant rule https://github.com/AdguardTeam/AdguardFilters/commit/24aa592f8b45e5abb0df5c6106bc1a228d42c0c5
=> Removed obsolete exclusions, updated the exclusion for the French folter

filters/ThirdParty/filter_227_List-KR/metadata.json, filters/ThirdParty/filter_227_List-KR/template.txt
=> Change List-KR subscription URL

custom_platforms.js
https://github.com/AdguardTeam/FiltersRegistry/issues/756
=> Remove some unsupported modifiers for android content blocker

filters/ThirdParty/filter_227_List-KR/template.txt
Fix https://github.com/List-KR/List-KR/issues/643
Reference: https://github.com/List-KR/List-KR/commit/f9b8cd180b3d72b0ea4d5a16cfd3ba6579d98339
=> Fix tv.nate.com advertisement on AdGuard for iOS

filters/ThirdParty/filter_233_AdblockListFinland/template.txt
I've made some changes in the Finnish list repo, so that's why url update.
=> Update The Finnish list source

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/149677#issuecomment-1546881388 https://github.com/banbendalao/ADgk/issues/74
=> Excluded bad rule in ADgk Mobile China list

package.json, yarn.lock
build locally please
to ensure the proper deps versions are used, run before build
```
rm -rf node_modules
yarn install
```
=> revert compiler to v1.1.82

custom_platforms.js
Reverts AdguardTeam/FiltersRegistry#807
=> Revert "Fix MS Edge  removeRulePatterns"

README.md
https://github.com/AdguardTeam/FiltersRegistry/issues/775
=> Adding some details to the custom_platforms description

custom_platforms.js
=> Synced custom_platforms.js with default config

package.json, yarn.lock
run the build please and check there is no problem
nothing special about this update, just new version of scriptlets and tsurlfilter (to keep them up to date):
https://github.com/AdguardTeam/FiltersCompiler/releases/tag/v1.1.92
=> update compiler to v1.1.92

package.json, yarn.lock
Update should fix this bug
https://github.com/AdguardTeam/FiltersCompiler/issues/185
=> Update compiler to v1.1.93

package.json, yarn.lock
as usual run build and check the report.txt please — previously invalid scriptlet rules should be valid now
=> update compiler to v1.1.96

filters/filter_3_Spyware/template.txt
Related to https://github.com/AdguardTeam/AdguardFilters/pull/163542.
Will be opened when the pr above is merged.
=> Adding a new file for cname

package.json, yarn.lock
support `$permissions` modifier so rules with it should no longer be considered as invalid
=> update compiler to v1.1.104

package.json, yarn.lock
related issues:
https://github.com/AdguardTeam/FiltersCompiler/issues/198
https://github.com/AdguardTeam/FiltersCompiler/issues/199
https://github.com/AdguardTeam/FiltersCompiler/issues/201
=> update compiler to v1.1.115

.eslintignore, .eslintrc, .github/workflows/workflow.yaml, .gitignore, custom_platforms.js, index.js, package.json, scripts/translations/converter.js, utils/strings.js, validate-locales.js, validate.js, yarn.lock
=> add eslint

filters/exclusions.txt
Fix https://github.com/AdguardTeam/FiltersRegistry/issues/858
=> Exclude youtube-related filters in YousList

custom_platforms.js, package.json, yarn.lock
\+ skip unblocking important rules for ubo as unsupported:
https://github.com/AdguardTeam/FiltersCompiler/issues/200
=> update compiler to v1.1.119

filters/ThirdParty/filter_122_FanboysAnnoyances/metadata.json
Fix #867
Fix https://github.com/AdguardTeam/AdguardFilters/issues/168277
=> Increase trust level of Fanboy's Annoyance filters list

filters/ThirdParty/filter_218_EstonianList/metadata.json
Reverts AdguardTeam/FiltersRegistry#860
It's alive.
=> Revert "Temporary disable Estonian list"

filters/ThirdParty/filter_201_WebAnnoyancesUltralist/metadata.json
Related to https://github.com/AdguardTeam/FiltersRegistry/pull/871
=> Added 'obsolete' tag for Web Annoyances Ultralist

filters/ThirdParty/filter_215_FanboysEnancedTrackingList/metadata.json, locales/en/filters.json
no longer support
https://fanboy.co.nz/enhancedstats.txt
=> Disable Fanboy's Enhanced Tracking List

filters/ThirdParty/filter_101_EasyList/metadata.json, filters/ThirdParty/filter_103_BulgarianList/metadata.json, filters/ThirdParty/filter_106_EasyListDutch/metadata.json, filters/ThirdParty/filter_107_EasyListGermany/metadata.json, filters/ThirdParty/filter_109_EasyListItaly/metadata.json, filters/ThirdParty/filter_112_ListeAR/metadata.json, filters/ThirdParty/filter_113_ListeFR/metadata.json, filters/ThirdParty/filter_118_EasyPrivacy/metadata.json, filters/ThirdParty/filter_122_FanboysAnnoyances/metadata.json, filters/ThirdParty/filter_123_FanboysSocialBlockingList/metadata.json, filters/ThirdParty/filter_207_AdblockWarningRemovalList/metadata.json, filters/ThirdParty/filter_214_ABPVNList/metadata.json, filters/ThirdParty/filter_231_EasyListSpanish/metadata.json, filters/ThirdParty/filter_241_FanboyCookiemonster/metadata.json, filters/ThirdParty/filter_246_EasyListPolish/metadata.json
As requested, changed some filters homepage to gh repos.
=> Homepage for Easylist and related filters

package.json, yarn.lock
new compiler version with updated scriptlets: 
https://github.com/AdguardTeam/Scriptlets/blob/master/CHANGELOG.md
- - -
related: https://github.com/AdguardTeam/FiltersCompiler/issues/181
=> update compiler to v1.1.123

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/174196
=> fix https://github.com/AdguardTeam/AdguardFilters/issues/174196

filters/ThirdParty/filter_250_DandelionSproutAnnoyances/metadata.json
Reverts AdguardTeam/FiltersRegistry#913
=> Revert "Disabling `Dandelion Sprout's Annoyances List`"

filters/ThirdParty/filter_250_DandelionSproutAnnoyances/metadata.json
Reverts AdguardTeam/FiltersRegistry#914
=> Disabling `Dandelion Sprout's Annoyances List`

filters/ThirdParty/filter_242_NoCoin/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/issues/917
=> Disabling `Nocoin Filter List`

package.json, yarn.lock
https://github.com/AdguardTeam/FiltersCompiler/blob/master/CHANGELOG.md
=> update compiler to v1.1.127

filters/ThirdParty/filter_227_List-KR/trusted-rules.txt
https://github.com/List-KR/List-KR/commit/2062fc3357077a33cb5a115205c55faa66c7de90
=> anti-adblock: chzzk.naver.com

package.json, yarn.lock
add `$header` modifier support
=> update compiler to v1.1.129

filters/ThirdParty/filter_256_Scam_Blocklist/template.txt
Reverts AdguardTeam/FiltersRegistry#947
https://github.com/AdguardTeam/FiltersRegistry/issues/925#issuecomment-2061463864
**Merge only when `$all` modifiers will be removed from**
https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt
=> Revert "Fixed 256 Scam Blocklist by DurableNapkin"

filters/filter_2_Base/template.txt
Fix https://github.com/AdguardTeam/FiltersRegistry/issues/841#issuecomment-1798120751
Fix https://github.com/List-KR/List-KR/issues/909#issuecomment-2067629868
=> Add notOptimized option for allowlist_stealth.txt

filters/filter_2_Base/template.txt
Reverts AdguardTeam/FiltersRegistry#949
=> Revert "Add notOptimized option for allowlist_stealth.txt"

package.json, yarn.lock
compiler update with improved logging of errors which may happen during include directive resolving
=> update compiler to v1.1.136

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/180570
=> Breakage at mfront.homeplus.co.kr

filters/ThirdParty/filter_203_hufilter/metadata.json, filters/ThirdParty/filter_203_hufilter/template.txt
Reference: https://github.com/hufilter/hufilter-dev/issues/461
=> Update subscription URL for hufilter

package.json, yarn.lock
https://github.com/AdguardTeam/FiltersCompiler/blob/v1.1.140/CHANGELOG.md#v11140---2024-07-01
=> update compiler to v1.1.140

package.json, yarn.lock
https://github.com/AdguardTeam/FiltersCompiler/blob/v1.1.141/CHANGELOG.md
=> update compiler to v1.1.141

scripts/build/custom_platforms.js
if changes are ok, I will update the default config in the compiler and update it. so the PR waits for a preparatory approve, that's why it is WIP for now
=> use specific `adguard_ext_chromium_mv3` constant for `!#if` directive for `ext_chromium_mv3` platform

package.json, yarn.lock
https://github.com/AdguardTeam/FiltersCompiler/blob/master/CHANGELOG.md#v11142---2024-07-12
=> update compiler to v1.1.142

package.json, yarn.lock
https://github.com/AdguardTeam/FiltersCompiler/blob/v1.1.143/CHANGELOG.md
=> update compiler to v1.1.143

optimization_config.json
=> Fixed optimization config for 221, 237, 241; removed 229

optimization_config.json
Reverts AdguardTeam/FiltersRegistry#987
=> Revert "Fixed optimization config for 221, 237, 241; removed 229"

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/commit/d51106f5ee1de91e792ebbca6a18ccc98738fe64
=> Exclude baits removed from EasyList

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/188964
=> Fix kimcartoon - bait rule 

filters/exclusions.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/1002
=> Fix #1002 kissasian.com.ru

filters/ThirdParty/filter_217_PolskiFiltrCookies/metadata.json
https://github.com/AdguardTeam/FiltersRegistry/issues/1015
=> Add Polish GDPR-Cookies Filters to v5 #1015

scripts/build/custom_platforms.js
https://github.com/AdguardTeam/FiltersCompiler/issues/231
=> Exclude $redirect-rule from filters for MV3 extension

package.json, yarn.lock
Related to https://github.com/AdguardTeam/FiltersCompiler/issues/231
=> update compiler to v1.1.148

optimization_config.json
Reverts AdguardTeam/FiltersRegistry#1023
=> Revert "Revert minPercent for 6, 16, 22, 113, 122, 123"

filters/ThirdParty/filter_204_PeterLowesList/metadata.json
Reverts AdguardTeam/FiltersRegistry#1034
=> Revert "Temporary disabled `Peter Lowe's Blocklist`"

scripts/wildcard-domain-processor/top-tld.ts
https://github.com/AdguardTeam/FiltersRegistry/issues/1038
=> Fix #1038 add TLDs

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/194839
=> Fix https://github.com/AdguardTeam/AdguardFilters/issues/194839

README.md
https://github.com/AdguardTeam/FiltersRegistry#expanding-wildcard-domains
https://uploads.adguard.org/sl4xmIvrvCex8PQ0Xe.png
=> fix readme list

.cursorignore, .gitignore
https://www.cursor.com/security#codebase-indexing
=> add cursorignore file

filters/ThirdParty/filter_247_PolishRssFilters/metadata.json
It was from this https://github.com/AdguardTeam/FiltersRegistry/pull/1059.
We'll be able to decide whether to merge it or not after we get feedback https://github.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/issues/274.
=> Enabled `Polish Anti-Annoying Special Supplement`

package.json, yarn.lock
fix of https://github.com/AdguardTeam/FiltersCompiler/issues/243
to check difference, run build for filter `3` locally or check the build logs
=> update compiler to v1.1.153

scripts/wildcard-domain-processor/wildcard-expander.ts
https://github.com/AdguardTeam/FiltersRegistry/issues/1063
=> #1063 add comment

package.json, scripts/build/custom_platforms.js, scripts/build/patches.js, yarn.lock
related: 
https://github.com/AdguardTeam/FiltersCompiler/issues/247
=> AG-41814 add 'mac_v3' platform support

filters/filter_10_Useful/template.txt, filters/filter_11_Mobile/template.txt, filters/filter_13_Turkish/template.txt, filters/filter_14_Annoyances/template.txt, filters/filter_16_French/template.txt, filters/filter_17_TrackParam/template.txt, filters/filter_18_Annoyances_Cookies/template.txt, filters/filter_19_Annoyances_Popups/template.txt, filters/filter_1_Russian/template.txt, filters/filter_20_Annoyances_MobileApp/template.txt, filters/filter_21_Annoyances_Other/template.txt, filters/filter_224_Chinese/template.txt, filters/filter_22_Annoyances_Widgets/template.txt, filters/filter_23_Ukrainian/template.txt, filters/filter_24_QuickFixes/template.txt, filters/filter_2_Base/template.txt, filters/filter_3_Spyware/template.txt, filters/filter_4_Social/template.txt, filters/filter_5_Experimental/template.txt, filters/filter_6_German/template.txt, filters/filter_7_Japanese/template.txt, filters/filter_8_Dutch/template.txt, filters/filter_9_Spanish/template.txt
Related to https://github.com/AdguardTeam/AdguardFilters/pull/205730
Build was successful.
=> Changed pathes to use GitHub Pages repository URLs

locales/de/filters.json
related to https://github.com/AdguardTeam/AdguardBrowserExtension/issues/3216
=> update de locale

.github/workflows/build-3p.yaml, .github/workflows/build-adguard.yaml
Added Slack notifications workflow for
* Build AdGuard filters
* Build Third-party filters
=> Add Slack notification on failure

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/207941
=> Fix adobe.com

filters/ThirdParty/filter_227_List-KR/trusted-rules.txt
Refer https://github.com/AdguardTeam/AdguardFilters/issues/207568
=> ad: tv.nate.com

README.md, scripts/wildcard-domain-processor/wildcard-expander.ts
=> improve comments about wildcard expansion

filters/ThirdParty/filter_227_List-KR/trusted-rules.txt
https://github.com/AdguardTeam/AdguardFilters/issues/204843#issuecomment-3077532042
```typescript
window.MutationObserver = new Proxy(window.MutationObserver, {
construct(Target: typeof MutationObserver, Args: ConstructorParameters<typeof MutationObserver>) {
let Stringified = Args[0].toString()
if (Stringified.includes('cs:') && Stringified.includes('gl:') && Stringified.includes('ne:') && Stringified.includes('dg:')) {
return new Promise(() => {})
}
return Reflect.construct(Target, Args)
}
})
```
https://github.com/AdguardTeam/Scriptlets/issues/461#issuecomment-3081859146
=> Fix map.naver.com

filters/ThirdParty/filter_227_List-KR/trusted-rules.txt
Fix https://github.com/AdguardTeam/FiltersRegistry/pull/1109#issuecomment-3082853303
=> Fix map.naver.com possible breakage
