AdguardTeam/FiltersRegistry

package.json
Extended Css rules are now skipped for content-blocker platforms
=> updated compiler - content blockers omit extended css

filters/filter_15_DnsFilter/template.txt
Guys, we're going to host AdGuard DNS code in the old location so the SDNS filter has a new location now:
https://github.com/AdguardTeam/AdGuardSDNSFilter
=> Change SDNS filter source

filters/exclusions.txt
It fixes embedded Tweets on:
https://www-rosenheim24-de.cdn.ampproject.org/v/s/www.rosenheim24.de/bayern/muenchen-kurzschluesse-legen-s-bahn-muenchen-lahm-passagiere-stundenlang-eingeschlossen-10617078.amp.html?usqp=mq331AQGCAEoAVgB&amp_js_v=0.1#origin=https://www.google.de&cid=1&prerenderSize=1&visibilityState=visible&paddingTop=54&history=1&p2r=0&horizontalScrolling=0&csi=1&storage=1&viewerUrl=https://www.google.de/amp/s/www.rosenheim24.de/bayern/muenchen-kurzschluesse-legen-s-bahn-muenchen-lahm-passagiere-stundenlang-eingeschlossen-10617078.amp.html&cap=swipe,navigateTo,fragment,handshakepoll,cid,replaceUrl
and not working video on:
https://praxistipps.chip.de/microsoft-edge-werbung-blockieren-so-klappts_42804?layout=amp
and probably other issues on "AMP" websites.
=> Fix https://github.com/AdguardTeam/AdguardFilters/issues/25529

filters/ThirdParty/filter_243_FrellwitSwedish/metadata.json, filters/ThirdParty/filter_249_NorwegianList/metadata.json, locales/en/tags.json, tags/metadata.json
There's been some updates in my Norwegian list, that I feel could need to be reflected in the various desktop/app/extension versions of AdGuard.
* In December 2018, after realising that Schack had most likely ceased work on his Danish adblock list, and that roughly a quarter of his list's entries had ceased to work or were for defunct domains, I decided to expand my list to also include Danish sites. While I was at it, I wrote Icelandic entries as well (initially as a self-challenge to see how much I could shrink the *Icelandic ABP List* list), and a handful of Faroese ones. Therefore the list's name is now officially **Dandelion Sprout's Nordic filters** (for tidier websites).
* * However, it does *not* cover (non-Sami) Finnish or Swedish websites, as the currently maintained lists for …
=> Updated the Nordic (prev. Norwegian) list's metadata

filters/general_js_api.txt
It now removes cookies from all subdomains, not just from the current domain.
See the change here:
https://gist.github.com/ameshkov/a75d128175e3427ecc1eb810cf5dac5e/revisions
=> Improved AG_removeCookie

filters/general_js_api.js, filters/general_js_api.txt
1. Added `general_js_api.js` file with the non-minified functions implementations.
2. Changed `AG_abortInlineScript` implementation -- added `debug` parameter. If it is specified, the script will print a line to the browser console when the work is done.  
3. Added `AG_abortOnPropertyWrite` and `AG_abortOnPropertyRead` functions.
4. **`debug`** is not supposed to be used in the filter lists. It is useful for debugging purposes though.
=> Added AG_onPropertyRead/Write

filters/ThirdParty/filter_227_List-KR/metadata.json, filters/ThirdParty/filter_244_YousList/metadata.json
originally list kr was an recommended kor ad filter but it was replaced with a yous list after list kr filter is removed for maintainers afk. but now that its back and maybe we can set list kr as an recommended kor ad filter.
=> list kr official filter

filters/exclusions.txt
Guys, this is a quick fix for no images in articles.
See the example here:
https://www.windowscentral.com/best-laptop-touchpad
Plz report this to Easylist and merge this PR afterward.
=> fix windowscentral images lazy load

filters/ThirdParty/filter_121_VoidGr/metadata.json
I've temporarily disabled this filter because it was messing up the build (for some reason, `https://www.void.gr/kargig/void-gr-filters.txt` couldn't be downloaded on the build server).
We should try enabling it back in a couple of days.
I created this PR to test the build on Travis, and so that we don't forget to enable it back.
=> enable back void.gr

filters/ThirdParty/filter_219_ChinaListAndEasyList/metadata.json
It seems that http://sub.adtchrome.com/adt-chinalist-easylist.txt loads correctly now, so I think that we can re-enable `ChinaList+EasyList`, or not yet?
=> Re-enabled ChinaList+EasyList

filters/exclusions.txt
Not a tracker. Causes some issues.
=> Excluded `/generate_204$image,other,script` rule from EasyPrivacy

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/42485
$document block rule has higher priority than $important exclusion rule. Site only serves AdFender picture file.
=> fix finanznachrichten.de

filters/ThirdParty/filter_201_WebAnnoyancesUltralist/metadata.json
Due to issue with `!#include` directive probably.
=> Disable Web Annoyances Ultralist temporary

filters/ThirdParty/filter_121_VoidGr/metadata.json
`Error: Error: include https://raw.githubusercontent.com/kargig/greek-adblockplus-filter/master/void-gr-filters.txt contains redirect directive: ! Redirect: https://www.void.gr/kargig/void-gr-filters.txt`
=> Temporary disable void.gr filter

filters/ThirdParty/filter_238_PolskiFiltrAdg/metadata.json
See: 
https://github.com/AdguardTeam/AdguardFilters/issues/51118#issuecomment-596214305
https://github.com/AdguardTeam/AdguardFilters/issues/51118#issuecomment-596975486
If it is a lot suggested to activate it manually, it may have the recommended flag (assuming it is activated when visiting Polish language pages).
I guess we could use the Windows / macOS platform:
"`!+  NOT_PLATFORM( )`" instead of `badfilter` / `important` modifiers in the supplement.
=> PolskiFiltrAdg trusted high level and deflaut activate?

filters/exclusions.txt
We have already `facebook.com#?#` in exclusions, but it looks like that some new rules was added to EasyList:
<details><summary>Code</summary>
```
facebook.com,facebookcorewwwi.onion#?#._6y8t:-abp-has(a[href="/ads/about/?entry_product=ad_preferences"])
facebook.com,facebookcorewwwi.onion#?#.ego_section:-abp-has(a[href^="/ad_"])
facebook.com,facebookcorewwwi.onion#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[ajaxify*="&ad_id="])
facebook.com,facebookcorewwwi.onion#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[data-hovercard^="/ajax/hovercard/page.php?id=152717608708800&"])
facebook.com,facebookcorewwwi.onion#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[data-hovercard^="/ajax/hovercard/page.php?id=1562919887258584&"])
facebook.com,facebookcorewwwi.onion#?#div[id^="hyperfeed_story_id_"]:-abp-has( …
```
=> Excluded Extended CSS rules for Facebook from third party filters

filters/ThirdParty/filter_120_AdBlockID/template.txt
Also we can change `trustLevel` to `High` and make this filter recommended. It is maintained and does not causes issues.
https://github.com/AdguardTeam/FiltersRegistry/issues/235
=> Fix #322 - Added uBO-specific source to AdBlockID filter

filters/exclusions.txt
Excluded $popup rule, because it causes issues on some websites.
Examples:
https://github.com/AdguardTeam/AdguardFilters/issues/55609
https://github.com/AdguardTeam/AdguardFilters/issues/55478#issuecomment-629828357
=> Excluded $popup rule

filters/ThirdParty/filter_201_WebAnnoyancesUltralist/metadata.json
look at our chat for details.
```
! syntax for latest ubo 1.27.5b1 on firefox
!#include filters/css_companion_filters.txt
!syntax fo all other blockers
!#include css_companion_filters.txt
```
=> Temporary disabled Web Annoyances Ultralist due to incompatible '!#include' directive

filters/ThirdParty/filter_103_BulgarianList/metadata.json, filters/ThirdParty/filter_103_BulgarianList/template.txt, filters/ThirdParty/filter_110_EasyListLithuania/metadata.json, filters/ThirdParty/filter_113_ListeFR/metadata.json, filters/ThirdParty/filter_114_ROList/metadata.json, filters/ThirdParty/filter_114_ROList/template.txt, filters/ThirdParty/filter_119_IcelandicABPList/metadata.json, filters/ThirdParty/filter_204_PeterLowesList/metadata.json, filters/ThirdParty/filter_205_SchacksAdblockPlusListe/metadata.json, filters/ThirdParty/filter_205_SchacksAdblockPlusListe/template.txt, filters/ThirdParty/filter_210_Spam404/metadata.json, filters/ThirdParty/filter_214_ABPVNList/metadata.json, filters/ThirdParty/filter_218_EstonianList/metadata.json, filters/ThirdParty/filter_218_EstonianList/template.txt, filters/ThirdParty/filter_219_ChinaListAndEasyList/metadata.json, filters/ThirdParty/filter_219_ChinaListAndEasyList/template.txt, filters/ThirdParty/filter_222_ABPPersian/metadata.json, filters/ThirdParty/filter_223_FanboySwedish/metadata.json, filters/ThirdParty/filter_225_fanboyAntifacebook/metadata.json, filters/ThirdParty/filter_226_FanboyVietnamese/metadata.json, filters/ThirdParty/filter_230_FanboyEspanol/metadata.json, filters/ThirdParty/filter_230_FanboyEspanol/template.txt, filters/ThirdParty/filter_239_FanboyAntifonts/metadata.json, filters/ThirdParty/filter_241_FanboyCookiemonster/metadata.json
Inspired by #334, I decided to fix and improve the metadata of a whole slew of lists in this repo.
Most affected were "ChinaList+EasyList" (now renamed "ADT ChinaList" by me, as it does not actually include EasyList), and "Fanboy's Spanish/Portuguese". However, around 20 other lists also saw their links be changed from HTTP to HTTPS, or even replaced entirely (e.g. in Liste FR's case).
I also marked "Fanboy's Swedish" and "Fanboy's Spanish/Portuguese" as obsolete, IIRC, as they had been marked as discontinued for more than 12 months; and rewrote some particularly odd-looking descriptions.
=> Huge metadata fixing

filters/ThirdParty/filter_249_NorwegianList/metadata.json
While fiddling around with AdGuard for Android during a bus ride today, I noticed that it still showed the link to the uBO list version on the list info screen (as seen in the screenshot below), instead of the AdGuard list version. So I've attempted to correct that now.
=> Corrected the "subscriptionUrl" link for my Nordic list

filters/exclusions.txt
`#$#abort-current-inline-script` — https://github.com/AdguardTeam/FiltersCompiler/issues/39
`scope` — [implemented](https://github.com/AdguardTeam/ExtendedCss/commit/925fc0170a9c8f2b4589256b34fa80d451cd1919#diff-6fd8b7afbef18123352836aedc684f8598fc9b87cfb4538f4297de1acdcc16ef) 6 weeks ago 
`xpath` — [implemented](https://github.com/AdguardTeam/ExtendedCss/blob/2029ff07758ee2fe3dd0be688991cc05cf5e7857/lib/extended-css-selector.js#L38) as well
=> fix abp exclusions

filters/ThirdParty/filter_120_AdBlockID/template.txt
Following up on this issue https://github.com/realodix/AdBlockID/pull/637, the AdBlockID Plus link should be removed.
=> Remove AdBlockID Plus

filters/exclusions.txt
https://github.com/AdguardTeam/SafariConverterLib/issues/4
First rule `||gamer.no/?module=Tumedia\DFProxy\Modules^`  was excluded via `$badfilter` here https://github.com/AdguardTeam/AdguardFilters/commit/8e83de3e7503adec5d3c819b737d2fe9e2f78e80
The rest of them are here, please check if they are correct.
=> Excluded rules from RU AdList and ChinaList+EasyList

filters/ThirdParty/filter_112_ListeAR/template.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/424
To reproduce issue:
1. Enable `Liste AR`
2. Go for example here -  [https://www.ebay-kleinanzeigen.de/s-anzeige/bkh-kitten-mit-blauen-augen/1657472638-136-4954](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.ebay-kleinanzeigen.de/s-anzeige/bkh-kitten-mit-blauen-augen/1657472638-136-4954)
3. Click on image
=> Fix #424 ebay-kleinanzeigen.de

filters/exclusions.txt
For example here - https://github.com/AdguardTeam/AdguardFilters/issues/77053
If `fundingchoicesmessages.google.com` is blocked and `div-gpt-ad` element is hidden then anti-adblock notice is displayed.
```
<div class="div-gpt-ad" style="width: 1px; height: 1px; position: absolute; left: -10000px; top: -10000px; z-index: -10000;"></div>
```
=> Excluded Google Contributor anti-adblock baits

filters/ThirdParty/filter_214_ABPVNList/metadata.json
It has no "recommended" tag and it seems not enabled for Vietnamese pages.
=> Make ABPVN List recommended

filters/exclusions.txt
original rule is absent in Easylist, exists in Bulgarian only.
After that, elemhide exclusions could be removed.
=> Excluded old BAB bait

filters/ThirdParty/filter_228_xinggsf/metadata.json
Our build fails because the domain `gitee.com` is not stable. Let's temporary disable it.
=> Temporary disable xinggsf

package.json, yarn.lock
[adguard-filters-compiler](https://github.com/AdguardTeam/FiltersCompiler/releases/tag/v1.1.23) with !#safari_cb_affinity validation
=> Update adguard-filters-compiler to v1.1.23

filters/ThirdParty/filter_122_FanboysAnnoyances/metadata.json, filters/ThirdParty/filter_122_FanboysAnnoyances/template.txt
This `https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt` returns `404` error.
=> Fanboys Annoyances - subscription url

filters/ThirdParty/filter_119_IcelandicABPList/metadata.json
According to the https://github.com/AdguardTeam/FiltersRegistry/issues/566#issuecomment-1031272201 and https://github.com/AdguardTeam/FiltersRegistry/issues/566#issuecomment-1031339492, I think we can leave only one recommended filter.
=> One recommended filter

filters/exclusions.txt
Filters fails to build in AdGuard for Safari
=> Fix EasyList Cookie List - bad rule

filters/exclusions.txt
Reverts AdguardTeam/FiltersRegistry#578
Fixed by filter's author
https://github.com/easylist/easylist/commit/1f87ac36cc1eee6d84e7ec1add7897d77f02beba
=> Revert "Fix EasyList Cookie List - bad rule"

filters/ThirdParty/filter_200_ABPJapaneseFilters/metadata.json, filters/ThirdParty/filter_200_ABPJapaneseFilters/template.txt, filters/ThirdParty/filter_205_SchacksAdblockPlusListe/metadata.json, filters/exclusions.txt
Excluded old only invalid rules. Disabled ABP Japanese Filter, Schacks Adblock Plus liste.
Added to exclusions.txt, because there are many unnecessary lines about invalide rules.
=> Excluded old only invalid rules. Disabled obsolete filters

filters/exclusions.txt
Blocking causes ads reinjection on some Ukrainian sites.
=> Fix znctrack.net https://github.com/AdguardTeam/AdguardFilters/issues/112370

package.json
disabled `$$` and `replace` rules for Firefox extension
=> Exclude replace temporarily

filters/filter_14_Annoyances/template.txt
TODO: Remove `\AdguardFilters\AnnoyancesFilter\sections\remains.txt` from filters after next filters build.
=> Removed obsolete file filter_14_Annoyances/remains.txt

filters/ThirdParty/filter_111_LatvianList/metadata.json
This reverts commit 9103f0298fc709703357ba42a9170dfbbae50dc6.
It seems this filter is available again.
=> Revert "temporary disabled the filter (#618)"

filters/ThirdParty/filter_218_EstonianList/metadata.json, filters/ThirdParty/filter_235_PersianBlocker/metadata.json
It is needed to automatically turn on these filters when a user visits sites.
=> Added recommended tags for two filters: `Persian Blocker` and `Estonian List`

filters/exclusions.txt
Looks like it's not needed due to the fix there https://github.com/xinggsf/Adblock-Plus-Rule/issues/52.
=> Remove unnecessary rule

filters/exclusions.txt
Related to 
https://github.com/AdguardTeam/CoreLibs/issues/880
https://github.com/AdguardTeam/CoreLibs/issues/1697
https://github.com/AdguardTeam/FiltersRegistry/issues/688
=> Removed obsolete esclusions for uBO's CSP rules

filters/exclusions.txt
Reverts AdguardTeam/FiltersRegistry#694
Bad rule was changed in the filter.
=> Revert "temporary exclusion of bad List-KR rule"

filters/ThirdParty/filter_208_Online_Malicious_URL_Blocklist/metadata.json
Despite that the link opens fine, filter build fails.
=> Temporary disable one filter `Online Malicious URL Blocklist`

package.json, yarn.lock
fixed `set-constant` ADG→UBO conversion for `emptyObj` and `emptyArr`
=> update compiler to v1.1.69

filters/exclusions.txt
For https://github.com/easylist/easylist/commit/c09ae084dc666529d0ae0e639836f423bd1231ff
BTW isn't `^` needed for `/###banner_ad$/` as well? Specific `###banner_ad` may be used by good reason.
=> exclude ##.adsbygoogle

filters/filter_1_Russian/template.txt
Related to https://github.com/AdguardTeam/FiltersRegistry/issues/735.
`news_exchange.txt` and `css_extended.txt` were removed. Now they are in `adservers.txt` and `specific.txt`.
`Old inclusions` will be removed after merging https://github.com/AdguardTeam/FiltersRegistry/pull/741.
=> New and old inclusions for `AdGuard Russian`

custom_platforms.js
https://github.com/AdguardTeam/FiltersRegistry/issues/756
~~[Regex](https://regex101.com/r/MhdbBh/1)~~ [replaced by simpler ones](https://github.com/AdguardTeam/FiltersRegistry/pull/757#discussion_r1136906671).
=> Remove some unsupported modifiers for iOS, Safari

filters/ThirdParty/filter_120_AdBlockID/template.txt
Previously on https://github.com/AdguardTeam/FiltersRegistry/pull/782, I forgot to change the url in the template.txt file
=> Update AdBlockID subscriptionUrl

custom_platforms.js
`,content` matches domains part of rule:
```
bridalgown.work,contents-group.work,...###ad3
```
https://github.com/AdguardTeam/FiltersCompiler/issues/178
=> improve ext_ublock removeRulePatterns

optimization_config.json
Fix an issue that AdGuard filter compiler for 3rd-party filters lists stopped working.
=> Set strict property of EasyList China to false

filters/ThirdParty/filter_209_ADgkMobileChinalist/metadata.json
We decided to disable the filter for the following reasons:
- there are low contribution activity
- the filter break sites
- issues have not been resolved for a long time.
=> Disabling `ADgk Mobile China list` filter

package.json, yarn.lock
fixed ADG→UBO conversion — scriptlet rule with `$path` modifier should not be converted into UBO syntax as unsupported
related:
https://github.com/AdguardTeam/FiltersCompiler/pull/182
=> update compiler to v1.1.90

package.json, yarn.lock
run build and check the report.txt please
the main change in this release — rules with UBO's $redirect priority, e.g. noop.js:99, are considered **valid**. they are going to be skipped during the applying
=> update compiler to v1.1.94

filters/filter_3_Spyware/template.txt
content blockers don't see domains in proxified urls (for example in Gmail)
=> Excluded mail trackers for content blockers

filters/ThirdParty/filter_201_WebAnnoyancesUltralist/metadata.json
I think that Web Annoyances Ultralist can be considered as an obsoleted filters list because it causes many incorrect blocking without maintenance and no related commits.
- https://github.com/yourduskquibbles/webannoyances/issues/516
=> Disable Web Annoyances Ultralist

package.json, yarn.lock
main changes: adding a new compiler's `@include` directive option — `/ignoreTrustLevel` https://github.com/AdguardTeam/FiltersCompiler/issues/202
docs:
https://github.com/AdguardTeam/FiltersCompiler?tab=readme-ov-file#include-directive
- - - 
https://github.com/AdguardTeam/FiltersCompiler/blob/master/CHANGELOG.md
=> update compiler to v1.1.121

scripts/build/custom_platforms.js
Do not remove `$removeparam` modifier if its value contains part of other modifiers.
Related to - https://github.com/AdguardTeam/AdguardFilters/issues/170206#issuecomment-1883912624
=> Improve removeRulePatterns

scripts/build/custom_platforms.js
We are currently releasing AdGuard 4.3.3, in which we have launched support for differential updates. To test the new scheme, we should extend the validity period of the filters for downloading updates through patches.
=> AG-29197: increase expires date for extension filters to 10 days (except safari)

filters/ThirdParty/filter_250_DandelionSproutAnnoyances/metadata.json
We have to disable the filter as it breaks the build, and the author hasn't responded yet.
=> Disabling `Dandelion Sprout's Annoyances List`

filters/exclusions.txt, filters/filter_3_Spyware/template.txt
* Changed and transferred from https://github.com/AdguardTeam/AdguardFilters/blob/b4c849d8c4f60606510203e9ff860a0df2930ebf/SpywareFilter/sections/cname_allowlist.txt
* Added `/exclude="../exclusions.txt"` to `cname_trackers` include of AdGuard Tracking Protection filter.
TODO: remove `SpywareFilter\sections\cname_allowlist.txt` from `AdguardFilters` after merge.
=> Excuded problematic domains from cname-trackers lists

filters/exclusions.txt
https://github.com/AdguardTeam/FiltersRegistry/pull/937#issuecomment-2039738772
=> Fix medlemskap.fagforbundet.no - incorrect blocking by CNAME

filters/ThirdParty/filter_227_List-KR/trusted-rules.txt
If you have a permission about managing chatting of a channel at chzzk.naver.com, you cannot see the administrator option after right-click a watcher's nickname.
However, If the trusted scriptlet rule is disabled or removed without any change, a watcher cannot see the PIP button in a live streaming player.
So, I push a temporary patch ( https://github.com/List-KR/List-KR/commit/bf0576fa3399ed8e3063f8c35a4cad990e47d8fc ) for the issue. 
After https://github.com/AdguardTeam/Scriptlets/issues/419 is resolved, it should be rechecked.
=> Fix chzzk.naver.com

filters/ThirdParty/filter_256_Scam_Blocklist/template.txt
Removed `/addModifiers="all"` because author added the necessary modifier, and now rules has 2 modifiers
`||1sttheworld.com^$all$all` - invalid rule
=> Fixed 256 Scam Blocklist by DurableNapkin

filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/185762
This domain hosts the player
`tubestatic.usco1621-b.com/static/ae-player`
=> Fix youtrannytube.com

filters/exclusions.txt
https://github.com/AdguardTeam/FiltersRegistry/issues/983
`g.163.com` blocks too much. For example - `reg.163.com` subdomains.
=> mail.163.com #983

scripts/wildcard-domain-processor/top-tld.ts
https://github.com/AdguardTeam/AdguardFilters/issues/197014
The right TLD (`.desi`) is not on the list, you can search on the lines:
`interxh.site,xhopen.com,xhspot.com,xhwide5.com`
https://filters.adtidy.org/extension/chromium-mv3/filters/18.txt
=> add desi TLD

filters/filter_14_Annoyances/metadata.json, filters/filter_15_DnsFilter/metadata.json
– 14 — AdGuard Annoyances filter
– 15 — AdGuard DNS filter, related to #800
https://github.com/AdguardTeam/FiltersRegistry#metadata
=> AG-29276 mark filter 14 and 15 as deprecated

filters/ThirdParty/filter_247_PolishRssFilters/metadata.json, filters/ThirdParty/filter_247_PolishRssFilters/template.txt
It's disabled due to [this](https://github.com/AdguardTeam/FiltersRegistry/actions/runs/13372087005/job/37342755428?pr=1057).
Reported https://github.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/issues/274.
=> Temporarily disabled `Polish Anti-Annoying Special Supplement`

package.json, scripts/build/patches.js, yarn.lock
We released a new `diff-builder`, version `1.1.0`, which now uses the system `diff` tool to help prevent problems with creating large patches.
And skip some redundant logs.
=> update diff-builder to 1.1.0 to use system diff utility for patches

package.json, yarn.lock
Since we are waiting for an update of the filtersCompiler (which uses diff-builder and filters-downloader internally), we need to lock the version of diff-builder explicitly to 1.1.0 until the update is released.
=> lock version of `diff-builder` to 1.1.0

package.json, scripts/build/custom_platforms.js, yarn.lock
(Corresponds to https://github.com/AdguardTeam/FiltersCompiler/pull/251; though we all know that I'm not going to make a third corresponding PR on BitBucket for this.)
Syncing AdGuard Base's uBO version in uBO gives these notes in uBO's logger as of uO 1.63.3b9:
So I figured, "Okay, I can at least give it a try to handle the `$removeheader`, `:matches-property` and generic style ones".
=> Handle syntaxes that uBO's logger consider to be unsupported

filters/exclusions.txt
Fix https://github.com/AdguardTeam/AdguardFilters/issues/207905 
Fixes problem with downloading files on `intel.com`.
File cannot be downloaded when `dogo.intel.com` is blocked (it comes from https://github.com/AdguardTeam/cname-trackers/blob/master/data/trackers/adobe-experience-cloud-(formerly-omniture).txt).
=> Fix intel.com
